[package]
name = "listdir"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.4"

[[example]]
name = "WalkDir"
path = "examples/WalkDir.rs"

[[example]]
name = "ListDir"
path = "examples/ListDir.rs"
