resolver: lts-22.43
packages:
- '.'
extra-deps:
#- streamly-core-0.2.0
#- streamly-0.10.0
#- fusion-plugin-0.2.6
- git: https://github.com/composewell/streamly
  commit: 8500b6446dae07e763370608625f26eff5c84600
- git: https://github.com/composewell/streamly
  commit: 8500b6446dae07e763370608625f26eff5c84600
  subdirs:
    - core
- git: https://github.com/composewell/streamly-fsevents
  commit: a7ef478ee6cdc8bad1893694eee7d02d2baf441b

rebuild-ghc-options: true

# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include

flags:
  mintty:
    Win32-2-13-1: false
