resolver: lts-16.12
packages:
- '.'
extra-deps:
- SDL-0.6.7.0@sha256:9d6ba75c0cab575ec38468c8277803983e985f9622437aeca6a53e6a7337a7d5,2045
- git: https://github.com/composewell/streamly.git
  commit: ac215ad43f9535636ca281fb3fb8b10d96b04ebb
#allow-newer: true
flags: {}
extra-package-dbs: []
rebuild-ghc-options: true
# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include
