resolver: lts-22.43
packages:
- '.'
extra-deps:
- fusion-plugin-0.2.7
- streamly-core-0.3.0
- streamly-0.11.0
- streamly-fsevents-0.1.0

#- git: https://github.com/composewell/streamly
#  commit: c7048326486e537908f9e6b7529f0d783014b7d9
#- git: https://github.com/composewell/streamly
#  commit: c7048326486e537908f9e6b7529f0d783014b7d9
#  subdirs:
#    - core
#- git: https://github.com/composewell/streamly-fsevents
#  commit: 7c06c187f0437e6857108c89fe74dc7cc53a0bac

rebuild-ghc-options: true

# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include

flags:
  mintty:
    Win32-2-13-1: false
