resolver: lts-16.31
packages:
- '.'
extra-deps:
- streamly-0.8.0@sha256:9784c80ee1ada51477520cabc4e92a0c76a6bb265f968a188f2fce818e7398e0,19654
# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include
