resolver: lts-20.13
packages:
- '.'
extra-deps:
- lockfree-queue-0.2.4
#- streamly-core-0.1.0
#- streamly-0.9.0
#- fusion-plugin-0.2.6
- git: https://github.com/composewell/streamly
  commit: 9a039b89c6b81300b2bd9c8765bf4bfa18e7c83c
- git: https://github.com/composewell/streamly
  commit: 9a039b89c6b81300b2bd9c8765bf4bfa18e7c83c
  subdirs:
    - core
# - lockfree-queue-0.2.4@sha256:156e7ccc193fc5d8b43f065e9cd31c3171c79ec25863283d546900d92930846d,2963
# - tasty-bench-0.3.2@sha256:e7678a19114e1ff5effbe9b96a4688fa085cee39a50003d1170ec271f83e0792,2209

rebuild-ghc-options: true

# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include

flags:
  mintty:
    Win32-2-13-1: false
