resolver: lts-22.43
packages:
- '.'
extra-deps:
#- streamly-core-0.2.0
#- streamly-0.10.0
#- fusion-plugin-0.2.6
- git: https://github.com/composewell/streamly
  commit: 64dd83c750e8eb77b0aa28127ccf04010a186b3a
- git: https://github.com/composewell/streamly
  commit: 64dd83c750e8eb77b0aa28127ccf04010a186b3a
  subdirs:
    - core
- git: https://github.com/composewell/streamly-fsevents
  commit: 71cc64256464ded84feb6ee592860a820e0a41d0

rebuild-ghc-options: true

# For mac ports installed SDL library on Mac OS X
extra-include-dirs:
- /opt/local/include

flags:
  mintty:
    Win32-2-13-1: false
