name: Haskell CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: GHC ${{ matrix.name }}
    env:
      CABAL_REINIT_CONFIG: y
      LC_ALL: C.UTF-8

      ENABLE_INSTALL: "n"

      STACK_UPGRADE: "y"

      CABAL_CHECK_RELAX: y
      CABAL_NO_SANDBOX: y
      CABAL_HACKAGE_MIRROR: hackage.haskell.org:http://hackage.fpcomplete.com

      PACKCHECK_LOCAL_PATH: "./packcheck.sh"
      PACKCHECK_GITHUB_URL: "https://raw.githubusercontent.com/harendra-kumar/packcheck"
      PACKCHECK_GITHUB_COMMIT: "563702bd02c41343dcd3dfcfef0845ca428a9240"

      BUILD: ${{ matrix.build }}
      GHCVER: ${{ matrix.ghc_version }}
      CABAL_BUILD_OPTIONS: ${{ matrix.cabal_build_options }}
      CABAL_PROJECT: ${{ matrix.cabal_project }}
      DISABLE_DOCS: ${{ matrix.disable_docs }}
      DISABLE_SDIST_GIT_CHECK: "y"

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        name: [8.10.2+macOS]
        cabal_version: ["3.2"]
        include:
          - name: 8.10.2+macOS
            ghc_version: 8.10.2
            build: cabal-v2
            cabal_project: cabal.project
    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc_version }}
        cabal-version: ${{ matrix.cabal_version }}

    - uses: actions/cache@v1
      name: Cache ~/.cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc_version }}-cabal

    - name: Download packcheck
      run: |
        # If a custom stack-yaml is specified, replace the default with that
        if test -e "$STACK_YAML"; then rm -f stack.yaml && ln -sv $STACK_YAML stack.yaml; else true; fi
        unset STACK_YAML

        # Get packcheck if needed
        CURL=$(which curl)
        PACKCHECK_URL=${PACKCHECK_GITHUB_URL}/${PACKCHECK_GITHUB_COMMIT}/packcheck.sh
        if test ! -e "$PACKCHECK_LOCAL_PATH"; then $CURL -sL -o "$PACKCHECK_LOCAL_PATH" $PACKCHECK_URL; fi;
        chmod +x $PACKCHECK_LOCAL_PATH

    - name: Run packcheck
      run: |
        bash -c "$PACKCHECK_LOCAL_PATH $BUILD"
